# Generated by Django 5.1.4 on 2024-12-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_link', models.URLField(max_length=500)),
                ('image_url', models.URLField(max_length=500)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('number_of_ratings', models.CharField(max_length=50)),
                ('specifications', models.TextField()),
            ],
        ),
    ]
